from .single_path import FULL_PATH_SYSTEM_PROMPT, FULL_PATH_PROMPTS
from .single_step import STEP_SEQUENCE_SYSTEM_PROMPT, STEP_SEQUENCE_PROMPTS
from .multi_dog_step import MULTI_DOG_STEP_SYSTEM_PROMPT, MULTI_DOG_STEP_PROMPTS

SYSTEM_PROMPTS_BY_MODE = {
    "Path": FULL_PATH_SYSTEM_PROMPT,
    "Steps": STEP_SEQUENCE_SYSTEM_PROMPT,
    "MultiDogSteps": MULTI_DOG_STEP_SYSTEM_PROMPT,
}

PROMPT_POOLS_BY_MODE = {
    "Path": FULL_PATH_PROMPTS,
    "Steps": STEP_SEQUENCE_PROMPTS,
    "MultiDogSteps": MULTI_DOG_STEP_PROMPTS,
}

__all__ = [
    "FULL_PATH_SYSTEM_PROMPT",
    "FULL_PATH_PROMPTS",
    "STEP_SEQUENCE_SYSTEM_PROMPT",
    "STEP_SEQUENCE_PROMPTS",
    "MULTI_DOG_STEP_SYSTEM_PROMPT",
    "MULTI_DOG_STEP_PROMPTS",
    "SYSTEM_PROMPTS_BY_MODE",
    "PROMPT_POOLS_BY_MODE",
]
